Patch 2
Systems-Platform/Documentation pull request #3
Opened 2021-02-11 12:07 UTC by sangeethaE

2021-02-12 19:51 UTC, RaveendraSeetharam requested changes
Please submit related vault-pass.yml file?

2021-02-12 19:51 UTC, RaveendraSeetharam commented on ansible-playbooks/psql.md
> +        - vault-pass.yml
Could you check in this file?

2021-02-12 19:52 UTC, RaveendraSeetharam commented on ansible-playbooks/psql.md
> +        - vault-pass.yml
Also, this file should not be checked into Documentation folder

2021-02-16 05:57 UTC, SangeethaEruparswapu commented
Closing puu request to update the branching

2021-02-16 05:58 UTC, SangeethaEruparswapu commented
close

2021-02-16 05:58 UTC, closed without merging